services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: fraud_mlflow
    volumes:
      - ./mlflow:/app/mlruns
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /app/mlruns
      --artifacts-destination /app/mlruns
      --serve-artifacts

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./src/api:/app/src/api

networks:
  default:
    name: fraud_network